"""update House table

Revision ID: 6c713ecb6f67
Revises: 4709f79b4dbd
Create Date: 2023-12-16 18:33:36.573325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c713ecb6f67'
down_revision = '4709f79b4dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('area_sqft', sa.Integer(), nullable=True))
    op.add_column('houses', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'price')
    op.drop_column('houses', 'area_sqft')
    # ### end Alembic commands ###
